### ISSUE TITLE
Need change log for each release.

### ISSUE THREAD

**Issue by cssmagic** [baixing/jedi#39]
所有 release： https://github.com/baixing/jedi/releases

光打 tag 不写 change log 恐怕不太好 :smiley:

**Comment by hax** [comment]
嗯，是有 change log 比较好。我得找个从 git log 自动生成 change log 的工具。

**Comment by amio** [comment]
可以考虑下用这个 https://github.com/ajoslin/conventional-changelog
只要 commit log 遵循这个规则 https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md
更好看的版本 http://karma-runner.github.io/0.12/dev/git-commit-msg.html

话说，我们的镐京也可以考虑引入下此类风格，还算简单，效果挺舒服。

**Comment by cssmagic** [comment]
@amio 你给出的资料很有参考价值，感谢！

**Comment by hax** [comment]
已经加入 changelog 和 old changelog！
