### ISSUE TITLE
Documentations need to be revised.

### ISSUE THREAD

**Issue by zpbx** [baixing/jedi#46]
现在 wiki 里的文档有很多内容都是错误的或过时的。比如 [Jedi 新手入门指南](https://github.com/baixing/jedi/wiki/Jedi-%E6%96%B0%E6%89%8B%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#1-%E6%A8%A1%E6%9D%BF%E7%BB%A7%E6%89%BF) 这篇文档里的 “模板继承” 段落，错到姥姥家了。

另需要补充 v1.0 的特性说明。

**Comment by hax** [comment]
dup #42
