### ISSUE TITLE
`:import` 指令的参数不能加引号？

### ISSUE THREAD

**Issue by cssmagic** [baixing/jedi#48]
代码这样写：

```js
:import 'skeleton.mobile'
```

会产生以下错误：

```js
Error: ENOENT, no such file or directory '/path/to/view/%27skeleton.mobile%27'
```

**Comment by hax** [comment]
嗯，实现时偷懒了。

**Comment by cssmagic** [comment]
这不符合预期啊……

而且我希望是在我们的代码规范中强制在此处加单引号的。

**Comment by hax** [comment]
其实另一个简单的选择是不需要引号，用跟url一样的规则（特殊字符转义）。

加引号的好处似乎只是看上去跟js和css比较一致。

**Comment by cssmagic** [comment]
愚以为加引号的好处有：

* 跨语言的习惯一致性：就像你说的 CSS、JS 等。我所谓的 “预期” 也是从这里来的。
* 语言自身的一致性：比如 `:import foo/bar` 中的 `foo/bar ` 为什么不是一个表达式，而是路径呢？

**Comment by hax** [comment]
第一点，jedi在语法上就跟js/css有比较多的不同，更接近于coffeescript/stylus。stylus也允许不加引号。（coffeescript因为是在有es6 module之前出现的，所以不存在特殊语法。）

第二点，jedi没有用`/`作为除号，所有的 a/b/c 形式一开始就保留了。

**Comment by hax** [comment]
其实路径除了 `:import` 指令外，还有导入外部代码（目前是php，考虑上也包括js）。现有的`:external`并没有处理这个问题，所以是不能使用namespace的。（也就是现在要用带有namespace的php函数等，需要手动包装一个全局函数。至于类就更麻烦了。只是因为历史原因，我们一开始的代码都不带有namespace。）我现在考虑要引入新的指令解决这个问题：#49 。这里涉及一个问题，php和js的package/namespace/module机制其实有比较大的差别，不过导入文件这个事情总是存在的。php有个有趣的做法是用 `A\B\C` 反向映射到文件路径。

**Comment by cssmagic** [comment]
> 第一点，jedi在语法上就跟js/css有比较多的不同，更接近于coffeescript/stylus。stylus也允许不加引号。

试了一下，Stylus 的 `@import` 和 `@require` 指令是需要加引号的，不加会报错。但 Jade 的 `include` 和 `extends` 指令的确是不需要的。

**Comment by cssmagic** [comment]
> 第二点，jedi没有用 `/` 作为除号……

我觉得这算一个槽点吧…… :joy: 

其它的有机会再聊。

**Comment by hax** [comment]
一开始就把 `/` 和 `*` 保留了，就是想跟 xpath 一样把 `/` 留给路径 :santa: 。而且模板里用乘除法非常罕见。另外，即使 `+` 和 `-` 也跟 scala（或css的calc） 一样，要求必须环绕空格。其实允许 `/` 在环绕空格时作为除法，并不和现在的语法冲突，只有 `*` 目前有冲突。

**Comment by hax** [comment]
> 试了一下，Stylus 的 `@import` 和 `@require` 指令是需要加引号的，不加会报错。

实际上 stylus 允许不加引号，但是只限于单词（即不能包含`/`、`.`）。它把`/`作为除号，意味着 `@import` 和 `@require` 后面跟着的是一个表达式（实际确实可以，比如 `@import dir + '/' + filename`）。但这里其实没必要且不应该允许运行时计算的表达式，而应仅限于某种形式的literal。

**Comment by zhujunsan** [comment]
要是决定要加空格了告诉我，编译缓存那边要改

**Comment by hax** [comment]
决定跟 jade 的 include/extends 一样，不加引号支持。这样也避免把路径认为是一个表达式。

**Comment by zhujunsan** [comment]
蛮好的 :D

-------------
Sent from San's mobile device

May we leave a world better than the one we are given.
