### ISSUE TITLE
如何处理php里的namespace？

### ISSUE THREAD

**Issue by HerringtonDarkholme** [baixing/jedi#54]
Current workaround

```
- use Namespace\SomeClass
:external SomeClass
```

Problem:
As `php -l` complains:

php: Fatal error: Cannot use `NameSpace\SomeClass` as `SomeClass` because the name is already in use

**Comment by hax** [comment]
计划下个版本（本周内）实现。

**Comment by HerringtonDarkholme** [comment]
这周就只剩两天了啊

**Comment by HerringtonDarkholme** [comment]
这个feature实现了么？

**Comment by hax** [comment]
已经合并到主干。
