### ISSUE TITLE
boolean attribute的写法太蛋疼

### ISSUE THREAD

**Issue by HerringtonDarkholme** [baixing/jedi#59]
```
input @name="maybedisabled" @disable if disabled
input @named="maybedisabled" if not disabled
```
啊,不好意思不能编过

```
:if disabled
	input @type="text" @name="hehe" @disabled
:else
	input @type="text" @name="hehe"
```

Jade

```jade
input(type="text", name="hehe", disabled=$disabled)
```

**Comment by hax** [comment]
Jedi is same as Jade in attribute binding.

```jedi
:let x = true, y = 1
	input
		@disabled = x
	div
		@data-a = (if y > 0 then 'a')
		@data-b = (if y <= 0 then 'b')
```

output:

```html
<input disabled><div data-a="a"></div>
```

Currently only simple case like `div.class if test` can use post `if`.

I plan to support complex form in the future.
```
// not implemented yet
?element.class = data if condition
  @attr = value if condition

// currently need to write as
:if condition
  element.class = data
    @attr = (if condition then value)
```

**Comment by HerringtonDarkholme** [comment]
> (9)标签的属性可以插入表达式，插入表达式时要使用双引号。

wiki上是这么写的啊！

**Comment by hax** [comment]
这个行为跟 Jade 是一样的。

识别 html 的属性是另一个层面的事情，比如可以报告 typo 啥的，识别 property 啥的（如 `@dataset={x:1, y:2}` 直接展开成 `@data-x=1 @data-y=2`），现在还没做。

**Comment by HerringtonDarkholme** [comment]
phpJade的行为好像不是这样的，compiler.php的882行可以看到是写死若干attributes的
使用js的jade行为与jedi一致，这个也是坑。到底好不好我得再想想

**Comment by hax** [comment]
原版jade的行为就是如此（区别只是它默认是按照xhtml格式输出的）。
新版pug还做了类似的一致化改变：object会按json输出（原本是只针对data-*，现在改为了所有属性）。

我认为对所有属性做一致性的处理是比较好的。更specific的规则应该基于类似类型检查之类的机制，是另一个层面的。
