### ISSUE TITLE
单行多tag最后的'text'解析不正确

### ISSUE THREAD

**Issue by HerringtonDarkholme** [baixing/jedi#63]
```
div > a @href='/link' 'text'
```

output

```php
echo   '<div>';                                                                // 1, 1 @ a.jedi
echo     '<a';                                                                 // 1, 7 @ a.jedi
echo       jedi_runtime_attribute('href', '/link'('text'));                    // 1, 3 @ a.jedi <-- 挂了
echo      '>';
echo     '</a>';
echo   '</div>';
```
Or by design again?

**Comment by HerringtonDarkholme** [comment]
无论如何不应该输出不合法的php代码，一定是bug

**Comment by hax** [comment]
1. 并不支持 `elem @attr=value 'text'`的写法，因为一行东西太多，且`@attr='text1' 'text2'`看不清。

2. `a @href="link"` 的写法也deprecated了（因为兼容性现在parser还支持）。可写作：
```jedi
a @@ href=link
```
或
```jedi
a
    @href = 'link'
```
即属性binding必须独立一行一个。

而 `element 'text'` 和 `element @@ attr1=value1 attr2=value2` 不可能在一行同时出现。

3. 输出不合法的php是bug，我看看怎么造成的。

**Comment by hax** [comment]
Oops，PHP。。。

`x y`等价于`x(y)`（单参数调用可省略括号）。而x可以是任何左值表达式，包括literal。比如在js里你可以写`'test'(1)`，不会报syntax error，只会是runtime error。

但是PHP的语法规则里x必须是symbol。所以`f(x)(y)`在php里也是语法错误，即使`f(x)`返回的是一个闭包。（必须写成`$c = f(x); $c();`。）

我稍微处理了一下这种情况，不过并不能完全消除所有edge case。

**Comment by HerringtonDarkholme** [comment]
为啥单参数调用可省略括号？

**Comment by hax** [comment]
> 为啥单参数调用可省略括号？

有一些语言是这样的（比如scalar/groovy）。一般目的是让dsl更好看。
所以最早在parser里保留了这个尝试。
我还没有决定是否要删掉这个语法糖。
