### ISSUE TITLE
需要定义external的行为

### ISSUE THREAD

**Issue by HerringtonDarkholme** [baixing/jedi#64]
jedi的抽象不能解决php的脑残，这个需要语法报错

	:external ImageStorage
	:let getConfig = ImageStorage.getImageServerConfig
		script = {qiniu: getConfig('qiniu'), upyun: getConfig('upyun')}
			!
				window.imageConfig = data;

```php
 call_user_func(function($getConfig) {                                         // 2, 1 @ a.jedi
   call_user_func(function ($context) {                                        // 3, 5 @ a.jedi
echo      '<script>';
echo       'void function(data){';
echo        '', "\n";                                                          // 4, 9 @ a.jedi
echo        'window.imageConfig = data;', "\n";
echo       '}(', json_encode($context, 0x100), ')';
echo      '</script>';
   }, (object)['qiniu' => $getConfig('qiniu'), 'upyun' => $getConfig('upyun')]);
 }, ImageStorage::getImageServerConfig);


```

**Comment by hax** [comment]
这个没法报语法错误。因为 `getImageServerConfig` 也可能是个属性，其值是个闭包，那么就是可以正常调用的。

暂时想不出什么办法（除了去load并parse所引用的php源码去分析到底是个方法还是属性——工程浩大不现实），所以这个问题目前只好留给写代码的人自己。

**Comment by HerringtonDarkholme** [comment]
这是个leaky abstraction
还不如直接报错，函数闭包在百姓没人用，去掉问题不大
如果真的需要还不如保证`let a = b.c; a()`这个东西不可用

**Comment by hax** [comment]
这是一个外部对接问题，而不是leaky abstraction。这类似于c/pascal的call conversion或者[abi](https://en.wikipedia.org/wiki/Application_binary_interface)。

因为模板并不是要抽象掉php或js，而只是需要调用php/js的内容。

php这个问题比较大，是因为php语言设计得太挫。除了闭包问题，php有重名的怪癖，属性/方法/常量可以重名，导致外部调用无法在编译时确定到底访问的是什么，php自己的namespace就因此要用 `use const/function xxx`这样的脱裤子放屁的语法。

----

但是回到这个Case本身，即使是js，你也不能确保这代码可用，因为你不知道 `ImageStorage.getImageServerConfig()`是否用到了`this`。

简单来说，function/method并不是一个简单的值。

> 还不如保证let a = b.c; a()这个东西不可用

我不确定这是值得的。不过我可以试试看。
