### ISSUE TITLE
let语句不能new

### ISSUE THREAD

**Issue by HerringtonDarkholme** [baixing/jedi#66]
use case: NodeUrl

```
:external
:let url = new NodeUrl('heheh')
```

**Comment by hax** [comment]
如果只有`NodeUrl`一个case，倾向于在php层面加factory，如`NodeUrl::create()`。

一个不相关的事情：`NodeUrl`的抽象本来就是有问题的，它在url router之外干了类似反向router的事情。

**Comment by HerringtonDarkholme** [comment]
这事儿大师兄搞搞吧

**Comment by hax** [comment]
你如果确认没有其他use case，我就先close掉这个了。改造`NodeUrl`的问题我会在haojing里开issue。

**Comment by hax** [comment]
加入了 X.new 支持。如：
```jedi
:use a/Test
:d Test.new('hax').name
```
php编译结果：
```php
var_dump((new \a\Test('hax'))->name);
```
