### ISSUE TITLE
let语句中先前定义的变量不能用在后面

### ISSUE THREAD

**Issue by HerringtonDarkholme** [baixing/jedi#68]
:let username = 'My name', greeting = '{username}, hello!'

这样编出来是不对的，$greeting = "{$data->username}"

**Comment by hax** [comment]
by design.

实现非嵌套`let`后，直接写成
```jedi
:let username = 'My name'
:let greeting = "{username}, hello!"
```

另外实现了解构之后，我会取消原来的一行多个声明的语法。如果需要一行写相关的多个声明，这样：
```jedi
:let [male, female] = ['M', 'F']
```
