### ISSUE TITLE
`npm install` fails on the jedi repo on PowerPC

### ISSUE THREAD

**Issue by sarveshtamba** [baixing/jedi#81]
Facing the following error while running `npm install` on the jedi repo on PowerPC:-
```
> jedi@1.0.0-rc6.4 postinstall /home/tester/jedi
> ./cli/jedi --version

jedi development version
Error: Cannot find module './lib/ometa-js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at load (/home/tester/jedi/load.js:13:3)
    at Object.<anonymous> (/home/tester/jedi/cli/jedi:2:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jedi@1.0.0-rc6.4 postinstall: `./cli/jedi --version`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jedi@1.0.0-rc6.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-11T09_14_23_141Z-debug.log
```
I tried building ometa-js from `https://github.com/alexwarth/ometa-js` and `https://github.com/veged/ometa-js` as well. However both of these do not help much and I am still facing the same error.
Any inputs on resolving this would be highly appreciated.

**Comment by hax** [comment]
You should use `git submodule` to get a revised version of ometa-js.

Anyway, this project have been stopped and will not have further maintenance. I'm curious why u want to try this project :)

**Comment by sarveshtamba** [comment]
@hax trying this as a part of a requirement, is there any alternative equivalent package that we can try and which is well maintained currently?
Also I tried adding 'git submodule add' for ometa-js from https://github.com/alexwarth/ometa-js and https://github.com/veged/ometa-js, still facing the same error. Any idea?

**Comment by sarveshtamba** [comment]
@hax any inputs on this?

**Comment by hax** [comment]
@sarveshtamba You could contact me via johnhax at gmail dot com to discuss your requirement, thank you!

**Comment by hax** [comment]
About `git submodule`, see https://github.com/baixing/jedi/tree/master/lib which point to https://github.com/hax/ometa-js/tree/f70ecc6a354de1f6bc31e0979472491f1780d971 (my fork of ometa-js)

**Comment by sarveshtamba** [comment]
@hax I was able to download/clone submodule 'lib/ometa-js' using the following command:-
`git submodule update --init --recursive`

After this, `npm install` and `npm test` commands were successful.
Thanks for all your help.
